# Generated by Django 4.0.3 on 2022-03-31 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='state',
            new_name='is_done',
        ),
    ]
