# Generated by Django 4.0.3 on 2022-03-08 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='if_staff',
            new_name='is_staff',
        ),
    ]
